### ISSUE TITLE
Curly braces advice contains error

### ISSUE THREAD

**Issue by gavinsimpson** [JEFworks-Lab/R-style-guide#1]
You suggest putting `}` on it's own line and have this as a good example of R style:

``` r
# Good
if (a < d) {
    a <- (b + c) * d
}
else {
    a <- d
}
```

The immediate problem with this is that if entering this at the prompt or piping line by line into R then you get an error:

```
> # Good
> if (a < d) {
+     a <- (b + c) * d
+ }
> else {
Error: unexpected 'else' in "else"
>     a <- d
> }
Error: unexpected '}' in "}"
```

because the parser has no way to know that the `if()` block hasn't finished yet (because it is part of an `if else` block). To the parser, this looks like a complete `if()` call. The correct way to wrote this would be:

``` r
# Good
if (a < d) {
    a <- (b + c) * d
} else {
    a <- d
}
```

**Comment by JEFworks** [comment]
Hi Gavin,
You're absolutely right. I've updated that section to reflect your correction. Thanks!
Best,
Jean
